# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.define :shard01 do |shard01| 
    shard01.vm.box = "precise64"
    shard01.vm.box_url = "http://files.vagrantup.com/precise64.box"

    shard01.vm.network :bridged
    shard01.vm.host_name = "shard01"
    shard01.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "sharding-playground.pp"
    end
  end

  config.vm.define :shard02 do |shard02| 
    shard02.vm.box = "precise64"
    shard02.vm.box_url = "http://files.vagrantup.com/precise64.box"

    shard02.vm.network :bridged
    shard02.vm.host_name = "shard02"
    shard02.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "sharding-playground.pp"
    end
  end

  config.vm.define :shard03 do |shard03| 
    shard03.vm.box = "precise64"
    shard03.vm.box_url = "http://files.vagrantup.com/precise64.box"

    shard03.vm.network :bridged
    shard03.vm.host_name = "shard03"
    shard03.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "sharding-playground.pp"
    end
  end
  
  config.vm.define :server4 do |configsrv| 
    configsrv.vm.box = "precise64"
    configsrv.vm.box_url = "http://files.vagrantup.com/precise64.box"

    configsrv.vm.network :bridged
    configsrv.vm.host_name = "configsrv"
    configsrv.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "configserver-playground.pp"
    end
  end

end
